import { NextPage } from "next"
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import styles from '../../styles/pages/User.module.scss'
import Head from 'next/head'
import Image from 'next/image'
import man from '../../public/images/users/man1.jpg'
import UserActivities from "../../components/UserActivities"
import UserSettings from "../../components/UserSettings"

import { useState } from 'react'



const User: NextPage = () => {
    const [ tab, setTab ] = useState<Number>(0)

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Navbar/>
                <div className={styles.main__content}>
                    <div className={styles.header}>
                        <div className={styles.userpic}>
                            <Image src={man} height={250} width={250} />
                        </div>
                        <span className={styles.username}>Paul Mouchel</span>
                    </div>
                    <div className={styles.tabs}>
                        <div className={`${styles.tab} ${tab === 0 && styles.active}`} onClick={() => setTab(0)}>Activité</div>
                        <div className={`${styles.tab} ${tab === 1 && styles.active}`} onClick={() => setTab(1)}>Paramètres</div>
                    </div>
                    <div className={styles['tab-content']}>
                        { tab === 0 && <UserActivities/> }
                        { tab === 0 && <UserSettings/> }
                    </div>

                  
                </div>
                <Footer/>

            </main>


        </div>
    )
}
  
export default User
  