import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/pages/Home.module.scss'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import CreatePost from '../components/CreatePost'
import Post from '../components/Post'
import api from '../api/posts'
import { useState, useEffect } from 'react'
import PostType from '../types/Post'

const Home: NextPage = () => {

    const [ posts , setPosts ] = useState<PostType[]>([])

    useEffect(() => {
        const fetchPosts = async () => {
            try {
                const response = await api.get('/posts')
                console.log(response.data)
                setPosts(response.data)
            } catch (error:unknown) {
                
                if (error.response) {
                    console.log(error.response.data)
                    console.log(error.response.status)
                    console.log(error.response.headers)
                } else {
                    if (typeof error === "string") {
                        console.log(`Error: ${error}`)
                    } else if (error instanceof Error) {
                        console.log(`Error: ${(error as Error).message}`)
                    }
                }
            }
        }
        fetchPosts()
    }, [])

    const sortByDate = (a:PostType, b:PostType) => {
        if (a.createdAt > b.createdAt)
            return -1
        if (a.createdAt < b.createdAt)
            return 1
        return 0
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Navbar/>
                <div className={styles.main__content}>
                    <CreatePost posts={posts} setPosts={setPosts}/>
                    { posts.sort(sortByDate).map((post, index) => 
                        <Post key={index} {...post}/>
                    )}
                </div>
                <Footer/>

            </main>


        </div>
    )
}

export default Home
