import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/pages/Home.module.scss'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import CreatePost from '../components/CreatePost'
import Post from '../components/Post'
import api from '../api/posts'
import { useState, useEffect } from 'react'

const Home: NextPage = () => {

    const [ posts , setPosts ] = useState([])

    useEffect(() => {
        const fetchPosts = async () => {
            try {
                const response = await api.get('/posts')
                console.log(response.data)
                setPosts(response.data)
            } catch (error) {
                if (error.response) {
                    console.log(error.response.data)
                    console.log(error.response.status)
                    console.log(error.response.headers)
                } else {
                    console.log(`Error: ${error.message}`)
                }
            }
        }
        fetchPosts()
    }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Navbar/>
                <div className={styles.main__content}>
                    <CreatePost/>
                    { posts.map((post, index) => 
                        <Post key={index} {...post}/>
                    )}
                </div>
                <Footer/>

            </main>


        </div>
    )
}

export default Home
